 deepeval test run test_example.py
Traceback (most recent call last):
  File "/Users/achhab16/Desktop/AI-Project/backend/venv/bin/deepeval", line 5, in <module>
    from deepeval.cli.main import app
  File "/Users/achhab16/Desktop/AI-Project/backend/venv/lib/python3.13/site-packages/deepeval/__init__.py", line 8, in <module>
    from deepeval.event import track
  File "/Users/achhab16/Desktop/AI-Project/backend/venv/lib/python3.13/site-packages/deepeval/event/__init__.py", line 1, in <module>
    from .event import track
  File "/Users/achhab16/Desktop/AI-Project/backend/venv/lib/python3.13/site-packages/deepeval/event/event.py", line 3, in <module>
    from deepeval.monitor.monitor import monitor
  File "/Users/achhab16/Desktop/AI-Project/backend/venv/lib/python3.13/site-packages/deepeval/monitor/__init__.py", line 1, in <module>
    from .monitor import monitor, a_monitor
  File "/Users/achhab16/Desktop/AI-Project/backend/venv/lib/python3.13/site-packages/deepeval/monitor/monitor.py", line 5, in <module>
    from deepeval.test_run.hyperparameters import process_hyperparameters
  File "/Users/achhab16/Desktop/AI-Project/backend/venv/lib/python3.13/site-packages/deepeval/test_run/__init__.py", line 1, in <module>
    from .test_run import (
    ...<6 lines>...
    )
  File "/Users/achhab16/Desktop/AI-Project/backend/venv/lib/python3.13/site-packages/deepeval/test_run/test_run.py", line 15, in <module>
    from deepeval.metrics import BaseMetric
  File "/Users/achhab16/Desktop/AI-Project/backend/venv/lib/python3.13/site-packages/deepeval/metrics/__init__.py", line 1, in <module>
    from .base_metric import (
    ...<3 lines>...
    )
  File "/Users/achhab16/Desktop/AI-Project/backend/venv/lib/python3.13/site-packages/deepeval/metrics/base_metric.py", line 10, in <module>
    from deepeval.models import DeepEvalBaseLLM
  File "/Users/achhab16/Desktop/AI-Project/backend/venv/lib/python3.13/site-packages/deepeval/models/__init__.py", line 7, in <module>
    from deepeval.models.gpt_model import GPTModel, MultimodalGPTModel
  File "/Users/achhab16/Desktop/AI-Project/backend/venv/lib/python3.13/site-packages/deepeval/models/gpt_model.py", line 2, in <module>
    from openai import OpenAI, AsyncOpenAI
ImportError: cannot import name 'OpenAI' from 'openai' (/Users/achhab16/Desktop/AI-Project/backend/venv/lib/python3.13/site-packages/openai/__init__.py)

getting this error on running deepeval test case on local. pls fix
